### ISSUE TITLE
Color code the Green Headings

### ISSUE THREAD

**Issue by Davidezrajay** [Greenstand/greenstand.org_website#44]
https://github.com/Greenstand/Design
green 1: 65744e
green 2: 7d8b53
green 3: c6d174
beige: f1eedb
brown: 5d4a4a

**Comment by sebastiangaertner** [comment]
they are all added to bootstraps _variables.scss and implemented.

**Comment by Davidezrajay** [comment]
@sebastiangaertner Awesome. Please close these issues when they are completed
