### ISSUE TITLE
Copy Editing

### ISSUE THREAD

**Issue by snacks** [Greenstand/greenstand.org_website#5]
This one needs some serious thought!

**Comment by rwi10** [comment]
Where are we organizing these thoughts? Im struggling with attempting to edit text in GH.

**Comment by sebastiangaertner** [comment]
The copy was ment to be on google drive if i am not mistaken. Gwen (snacks) could you point in the right direction. (trello is no longer used or?)

**Comment by Davidezrajay** [comment]
Let's be done with Trello, and keep everything here. 
And google docs.. https://docs.google.com/document/d/1huDqvM64hgYBHz6QFHqwQwhp2GPIeg5RmmF_046vGhE/edit?usp=sharing
