### ISSUE TITLE
Add "Sign up" for mailing list tab

### ISSUE THREAD

**Issue by Davidezrajay** [Greenstand/greenstand.org_website#61]
The https://www.ecocoin.com/ has this done nicely; "SIGN UP TO OUR MAILING LIST FOR THE LATEST NEWS ON ECO COIN" 

I guess ours would should say:
"SIGN UP TO OUR MAILING LIST FOR THE LATEST PROJECT NEWS"

**Comment by Davidezrajay** [comment]
This was to collect the email address for "news" I know you had made one that popped up as some point. The one box on this site is super un-intrusive: https://www.ecocoin.com/ has this done nicely; "SIGN UP TO OUR MAILING LIST FOR THE LATEST NEWS ON ECO COIN"

**Comment by sebastiangaertner** [comment]
Should we use mail chimp for that? 
--
Sent from myMail for Android Friday, 28 September 2018, 00:41AM +03:00 from DavidEzraJay  notifications@github.com :
