### ISSUE TITLE
Add Privacy Policy to footer or About?

### ISSUE THREAD

**Issue by Davidezrajay** [Greenstand/greenstand.org_website#65]
I like that both of these links are active. 

https://www.greenstand.org/privacy-policy
https://www.greenstand.org/wiki/privacy-policy/ (this one is not set in the app)

**Comment by sebastiangaertner** [comment]
It is working now. I changed it to a link within. its in the about section at the moment but can be moved without changing https://www.greenstand.org/privacy-policy (is now permanent)
