### ISSUE TITLE
The Team Page

### ISSUE THREAD

**Issue by Davidezrajay** [Greenstand/greenstand.org_website#66]
Who are we? This page is meant to answer this fundamental question. It is meant to keep track of who took what position. 

A static display of current team. (With images of Team)

With an option to open it up to team history

- Honors board (Top 3 monthly)  

- Top Contributors (All Time)

- Current Leads

**Comment by aistomina** [comment]
Here is the initial draft. Some notes based on research:

-bios need to be scannable, fun, and relatable. Categories still to be determined. Can write up details on this later. 

**Feedback, please. Thank you!**
[GS_TeamPage_Draft1.pdf](https://github.com/Greenstand/greenstand.org_website/files/2738361/GS_TeamPage_Draft1.pdf)

**Comment by sebastiangaertner** [comment]
Looks great. Can we have a call some time soon. Am setting up a new site 
with the current branding and would need some help there.
s.

**Comment by Davidezrajay** [comment]
Removed "open positions" from this page. That can be placed somewhere else
