### ISSUE TITLE
Review SEO suggestions 

### ISSUE THREAD

**Issue by Davidezrajay** [Greenstand/greenstand.org_website#75]
1. The meta description for greenstand.org is missing.
2. Robots.txt file is missing
3. No sitemap found in your robots.txt.
4. We found underscores in this URL and/or in your in-page URLs.
5. You need to improve no of Banklinks
6. You need to improve the social media channels to get maximum brand exposure.

**Comment by sebastiangaertner** [comment]
Added Sitemap https://greenstand.org/home?type=1533906435 and Robot file. Google Analytics and Google Search Console...
