### ISSUE TITLE
Add Financial PDF's to our website

### ISSUE THREAD

**Issue by Davidezrajay** [Greenstand/greenstand.org_website#77]
[Greenstand_990Ez_2015.pdf](https://github.com/Greenstand/greenstand.org_website/files/4297195/Greenstand_990Ez_2015.pdf)
[Greenstand_990Ez_2016.pdf](https://github.com/Greenstand/greenstand.org_website/files/4297196/Greenstand_990Ez_2016.pdf)
[Greenstand_990Ez_2017.pdf](https://github.com/Greenstand/greenstand.org_website/files/4297197/Greenstand_990Ez_2017.pdf)

**Comment by sebastiangaertner** [comment]
done... https://greenstand.org/47-3150283 link on each page in footer of website on the registration number.
